name: Terraform pipeline CI

on:
  push:
    branches:
      - main
      - release

  pull_request:
    branches:
      - main

  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read
  
  

jobs:
  my_job:
    name: Deploy to staging production strategy
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        
      - name: Terraform Init
        run: terraform init
        working-directory: ./Githubaction-Repository

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./Githubaction-Repository

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./Githubaction-Repository
