name: Terraform pipeline CI
on:
  push:
    branches:
    - main/*
    - release
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
jobs:
   my_job:  
    name: deploy to staging prodection strategy
    runs-on: ubuntu-22.04
  
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
           Terraform Init
           Terraform Validate
           Terraform Plan 
