name: Terraform Code Build Workflow-CI

on:
  push:
    branches:
      - main
      - feature

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  TerraformBuild:
    runs-on: ubuntu-latest

    steps:
      - name: Terraform Code Checkout
        uses: actions/checkout@v4

      - name: Terraform Hashicorp Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init Plan validate apply Infra Code Deployment
        working-directory: ./terraform
        run: |
          terraform init
          terraform validate
          terraform plan
          terraform apply --auto-approve
